export const PATH = {
    ROOT: "/",
    LOGIN: "/login",
    SIGNUP: "/signup",
    POS: "/pos",
    STORES: "/stores",
    REFERRAL: "/referral",
    LEADS: "/referral/leads",
    APP: "/app",
    ALL_APP: "/app/all",
    APP_ADS: "/app/ads",
    THEME: "/theme",
    RESOURCES: "/resources",
    TEAM: "/team",
    SETTING: "/setting",
    PAYOUT: "/payout",
    SUPPORT: "/support",
}